/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicSfxRouteImport } from './routes/api/public/sfx'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSfxRoute = ApiPublicSfxRouteImport.update({
  id: '/api/public/sfx',
  path: '/api/public/sfx',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/sfx': typeof ApiPublicSfxRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/sfx': typeof ApiPublicSfxRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/sfx': typeof ApiPublicSfxRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/public/sfx'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/public/sfx'
  id: '__root__' | '/' | '/api/public/sfx'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicSfxRoute: typeof ApiPublicSfxRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sfx': {
      id: '/api/public/sfx'
      path: '/api/public/sfx'
      fullPath: '/api/public/sfx'
      preLoaderRoute: typeof ApiPublicSfxRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicSfxRoute: ApiPublicSfxRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
